#!/usr/bin/env bash

CMD=$(basename $0)
if ! which yxlibinit > /dev/null; then
  echo "$(tput setaf 1)Error: yxshlib not found.$(tput sgr0)"
  echo "$(tput setaf 1)${CMD} is depend on yxshlib, But there is no installed YXSHLib script library locally.$(tput sgr0)"
  exit 1
fi

source yxlibinit 
source "${YXLIB_BIN}/yxnet" 


################################################################
# IP 地址并没有用, 这里保留这个格式，是为了方便替换host
################################################################
function github_host_list()
{
  cat <<EOF
140.82.112.26               alive.github.com
140.82.112.25               live.github.com
185.199.108.154             github.githubassets.com
140.82.114.22               central.github.com
185.199.109.133             desktop.githubusercontent.com
185.199.110.153             assets-cdn.github.com
185.199.110.133             camo.githubusercontent.com
185.199.109.133             github.map.fastly.net
151.101.77.194              github.global.ssl.fastly.net
20.205.243.166              gist.github.com
185.199.109.153             github.io
20.205.243.166              github.com
192.0.66.2                  github.blog
20.205.243.168              api.github.com
185.199.110.133             raw.githubusercontent.com
185.199.111.133             user-images.githubusercontent.com
185.199.110.133             favicons.githubusercontent.com
185.199.108.133             avatars5.githubusercontent.com
185.199.108.133             avatars4.githubusercontent.com
185.199.110.133             avatars3.githubusercontent.com
185.199.109.133             avatars2.githubusercontent.com
185.199.108.133             avatars1.githubusercontent.com
185.199.108.133             avatars0.githubusercontent.com
185.199.111.133             avatars.githubusercontent.com
20.205.243.165              codeload.github.com
3.5.25.37                   github-cloud.s3.amazonaws.com
52.216.39.9                 github-com.s3.amazonaws.com
54.231.203.81               github-production-release-asset-2e65be.s3.amazonaws.com
52.216.39.17                github-production-user-asset-6210df.s3.amazonaws.com
52.216.213.241              github-production-repository-file-5c1aeb.s3.amazonaws.com
185.199.108.153             githubstatus.com
140.82.113.18               github.community
20.43.185.14                github.dev
140.82.114.22               collector.github.com
13.107.42.16                pipelines.actions.githubusercontent.com
185.199.109.133             media.githubusercontent.com
185.199.111.133             cloud.githubusercontent.com
185.199.110.133             objects.githubusercontent.com
EOF
}



################################
# step 1. 验证主机状态 UP
# step 2. 验证DNS 查询IP
# step 3. 验证端口
# step 4. 验证 web 访问
# step 5. 输出明确错误原因
###############################
IFS_STORAGE="${IFS}"
IFS=$'\n'
for line in $(github_host_list); do
  host=$(echo "${line}" | awk '{print $2}')
  
  printf "%-60s" "${host} $(tput setaf 3)...$(tput sgr0)"
  if err_msg=$(yx_test_host --host "${host}" --no-ping --proto https 2>&1 >/dev/null); then
    echo -ne "\033[1G\033[K"
    printf "%-60s %s\n" ${host} ":$(tput setaf 2)Ok$(tput sgr0)"
  else
    
    # replace all '\n' with a white space but escape the last one.
    err_msg=$(echo -e "${err_msg}" | tr '\n' ' ' | sed '$s/ $/\n/' )
    
    echo -ne "\033[1G\033[K"
    if [ -n "${err_msg}" ]; then
      printf "%-60s %s (%s)\n" ${host} ":$(tput setaf 5)Failed$(tput sgr0)" "${err_msg}"
    else
      printf "%-60s %s\n" ${host} ":$(tput setaf 5)Failed$(tput sgr0)"
    fi
  fi
  
done
IFS="${IFS_STORAGE}"


